# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61b9798a8564fc7279c4a03b0dcee0a15559fbe7126fd0a2475cfe9aa358e657de2c4fd163a5abf9e18aed244c11833073a0ff7fe29a24782d214327f2ff15c1

test:
  secret_key_base: 76dc9a98927b5b866f91963f9dc1a555a4068729871dff2076edd01fb857d88bad17c7fe0d808ad4a3c6b175bd513cbd799a30dc0cb76ee14d8a33c5263fbeaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
